name: Create Release on Tag

on:
  push:
    tags:
      - 'v*.0'  # 监听符合 x.0 格式的标签

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create ZIP archive for EFI folder
        run: |
          zip -r EFI.zip EFI/  # 将 EFI 文件夹打包成 zip 文件

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: EFI.zip  # 上传压缩文件到 GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
