name: Create Release

on:
  push:
    paths:
      - 'EFI/**'  # 只有当 EFI 文件夹有文件变更时才触发

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
        
      - name: Check and delete existing tag if it exists
        run: |
          VERSION=$(date +'%Y%m%d')  # 使用当前日期作为版本号，格式为 yyyyMMdd
          # 删除本地已有的 tag
          git tag -d $VERSION || echo "Tag $VERSION does not exist locally"
          # 删除远程已有的 tag
          git push --delete origin $VERSION || echo "Tag $VERSION does not exist remotely"
        
      - name: Create a tag based on current date
        id: create_tag
        run: |
          VERSION=$(date +'%Y%m%d')  # 使用当前日期作为版本号，格式为 yyyyMMdd
          git tag $VERSION  # 创建标签
          git push origin $VERSION  # 推送标签到远程仓库
          echo "::set-output name=VERSION::$VERSION"  # 设置输出变量

      - name: Create ZIP archive for EFI folder
        run: |
          zip -r EFI.zip EFI/  # 将 EFI 文件夹打包成 zip 文件

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.VERSION }}  # 使用创建的 VERSION 变量作为 tag_name
          files: EFI.zip  # 上传压缩文件到 GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
