name: Create Release

on:
  push:
    paths:
      - 'EFI/**'  # 只有当 EFI 文件夹有文件变更时才触发


jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"
        
      - name: Create a tag based on current date
        run: |
          VERSION=$(date +'%Y%m%d')  # 使用当前日期作为版本号，格式为 yyyyMMdd
          git tag $VERSION  # 创建标签
          git push origin $VERSION  # 推送标签到远程

      - name: Create ZIP archive for EFI folder
        run: |
          zip -r EFI.zip EFI/  # 将 EFI 文件夹打包成 zip 文件

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: EFI.zip  # 上传压缩文件到 GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
